# Generated by Django 5.2.9 on 2026-01-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.BigAutoField(help_text='租户ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='租户编码（全局唯一，不可修改）', max_length=64, unique=True)),
                ('name', models.CharField(help_text='租户名称（允许编辑）', max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('SUSPENDED', '已停用')], db_index=True, default='ACTIVE', help_text='租户状态：ACTIVE=活跃，SUSPENDED=已停用', max_length=16)),
                ('plan', models.CharField(choices=[('BASIC', '基础版'), ('PRO', '专业版'), ('ENTERPRISE', '企业版')], db_index=True, default='BASIC', help_text='租户套餐：BASIC/PRO/ENTERPRISE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant',
                'indexes': [models.Index(fields=['status'], name='idx_tenant_status'), models.Index(fields=['plan'], name='idx_tenant_plan'), models.Index(fields=['name'], name='idx_tenant_name')],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('tenant_user_id', models.BigAutoField(help_text='租户成员ID', primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True, help_text='平台用户ID（FK → global_user.user_id）')),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('DISABLED', '已禁用')], default='ACTIVE', help_text='租户用户状态：ACTIVE=活跃，DISABLED=已禁用', max_length=16)),
                ('is_owner', models.BooleanField(default=False, help_text='是否该租户Owner（至少存在1个）')),
                ('last_login', models.DateTimeField(blank=True, help_text='最近一次进入该租户时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', help_text='租户', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_user',
                'indexes': [models.Index(fields=['tenant', 'user_id'], name='uk_tenant_user'), models.Index(fields=['tenant'], name='idx_tenant_user_tenant'), models.Index(fields=['user_id'], name='idx_tenant_user_user'), models.Index(fields=['tenant', 'status'], name='idx_tenant_user_status')],
                'unique_together': {('tenant', 'user_id')},
            },
        ),
    ]
