# Generated by Django 5.2.10 on 2026-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_rolepermission_resource_tree_node_fk'),
        ('resource_tree', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rolepermission',
            name='uk_role_perm',
        ),
        migrations.RemoveIndex(
            model_name='rolepermission',
            name='idx_perm_node',
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['tenant', 'role', 'resource_type', 'resource_tree_node'], name='uk_role_perm'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['tenant', 'resource_tree_node'], name='idx_perm_node'),
        ),
    ]
