# Generated by Django 5.2.10 on 2026-01-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRunInstance',
            fields=[
                ('task_run_id', models.BigAutoField(help_text='任务运行ID', primary_key=True, serialize=False)),
                ('task_type', models.CharField(db_index=True, help_text='任务类型（由 ExecutionRegistry 注册）', max_length=64)),
                ('task_id', models.BigIntegerField(db_index=True, help_text='业务任务ID（如 dataset_id/export_job_id/flow_run_id）')),
                ('tenant_id', models.BigIntegerField(db_index=True, help_text='租户ID（多租户隔离）')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('READY', '就绪（等待调度）'), ('RUNNING', '运行中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('CANCELLED', '已取消'), ('TIMEOUT', '超时')], db_index=True, default='PENDING', help_text='运行状态', max_length=16)),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='任务输入数据（JSON）')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='任务输出数据（JSON）')),
                ('error_code', models.CharField(blank=True, help_text='错误码（失败时）', max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, help_text='错误信息（失败时，截断2KB）', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='开始执行时间', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retry_count', models.IntegerField(default=0, help_text='重试次数')),
                ('max_retries', models.IntegerField(default=3, help_text='最大重试次数')),
                ('timeout_seconds', models.IntegerField(blank=True, help_text='超时时间（秒），null表示无超时', null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='幂等键（用于防重复执行）', max_length=128, null=True)),
                ('worker_id', models.CharField(blank=True, help_text='执行worker标识', max_length=128, null=True)),
                ('request_id', models.CharField(blank=True, help_text='请求ID（用于链路追踪）', max_length=128, null=True)),
            ],
            options={
                'db_table': 'task_run_instance',
                'indexes': [models.Index(fields=['task_type', 'task_id'], name='idx_task_run_type_id'), models.Index(fields=['tenant_id', 'status'], name='idx_task_run_tenant_status'), models.Index(fields=['status', 'created_at'], name='idx_task_run_status_created'), models.Index(fields=['idempotency_key'], name='idx_task_run_idempotency_key')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'READY', 'RUNNING'])), fields=('task_type', 'task_id', 'tenant_id'), name='uk_task_type_id_tenant_active')],
            },
        ),
        migrations.CreateModel(
            name='TaskRunLog',
            fields=[
                ('task_run_log_id', models.BigAutoField(help_text='任务运行日志ID', primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', help_text='日志级别', max_length=16)),
                ('message', models.TextField(help_text='日志消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='日志时间')),
                ('task_run', models.ForeignKey(help_text='关联的任务运行实例', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='execution.taskruninstance')),
            ],
            options={
                'db_table': 'task_run_log',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task_run', 'created_at'], name='idx_task_run_created')],
            },
        ),
    ]
