# Generated by Django 5.2.9 on 2026-01-25 00:00

import django.db.models.deletion
from django.db import migrations, models


def create_resource_tree_roots(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    ResourceTreeNode = apps.get_model("resource_tree", "ResourceTreeNode")

    scopes = ["TABLE", "FLOW", "DATASET", "DASHBOARD"]
    for tenant in Tenant.objects.all():
        for scope in scopes:
            node, _ = ResourceTreeNode.objects.get_or_create(
                tenant=tenant,
                scope=scope,
                parent_node=None,
                node_type="FOLDER",
                ref_type=None,
                ref_resource_id=None,
                defaults={
                    "name": "ROOT",
                    "sort_order": 0,
                    "depth": 0,
                    "path": "",
                },
            )
            if not node.path:
                node.path = f"/{node.node_id}/"
                node.depth = 0
                node.sort_order = 0
                node.name = "ROOT"
                node.save(update_fields=["path", "depth", "sort_order", "name"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceTreeNode",
            fields=[
                ("node_id", models.BigAutoField(help_text="节点ID", primary_key=True, serialize=False)),
                ("scope", models.CharField(choices=[("TABLE", "表"), ("FLOW", "流程"), ("DATASET", "数据集"), ("DASHBOARD", "仪表盘")], db_index=True, help_text="资源域（scope）", max_length=16)),
                ("node_type", models.CharField(choices=[("FOLDER", "文件夹"), ("RESOURCE", "资源")], default="FOLDER", help_text="节点类型：FOLDER/RESOURCE", max_length=16)),
                ("name", models.CharField(help_text="节点名称", max_length=128)),
                ("ref_type", models.CharField(blank=True, choices=[("TABLE", "表"), ("FLOW", "流程"), ("DATASET", "数据集"), ("DASHBOARD", "仪表盘")], help_text="资源类型（仅 node_type=RESOURCE 时存在）", max_length=16, null=True)),
                ("ref_resource_id", models.BigIntegerField(blank=True, help_text="资源引用ID（仅 node_type=RESOURCE 时存在）", null=True)),
                ("sort_order", models.IntegerField(default=0, help_text="同级排序")),
                ("path", models.CharField(blank=True, default="", help_text="节点路径缓存", max_length=512)),
                ("depth", models.IntegerField(default=0, help_text="层级深度")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parent_node", models.ForeignKey(blank=True, db_column="parent_node_id", help_text="父节点", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="resource_tree.resourcetreenode")),
                ("tenant", models.ForeignKey(db_column="tenant_id", help_text="租户", on_delete=django.db.models.deletion.CASCADE, related_name="resource_tree_nodes", to="tenants.tenant")),
            ],
            options={
                "db_table": "resource_tree_node",
                "indexes": [
                    models.Index(fields=["tenant", "scope", "parent_node"], name="idx_rt_parent"),
                    models.Index(fields=["tenant", "scope"], name="idx_rt_scope"),
                    models.Index(fields=["tenant", "ref_type", "ref_resource_id"], name="idx_rt_ref"),
                ],
            },
        ),
        migrations.RunPython(create_resource_tree_roots, reverse_code=migrations.RunPython.noop),
    ]

