# Generated by Django 5.2.9 on 2026-01-20 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(help_text='登录名（全局唯一，不可修改）', max_length=64, unique=True)),
                ('display_name', models.CharField(help_text='显示名称', max_length=64)),
                ('email', models.EmailField(help_text='邮箱（全局唯一）', max_length=128, unique=True)),
                ('password_hash', models.CharField(help_text='密码哈希', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('DISABLED', '已禁用')], db_index=True, default='ACTIVE', help_text='用户状态：ACTIVE=活跃，DISABLED=已禁用', max_length=16)),
                ('is_platform_admin', models.BooleanField(db_index=True, default=False, help_text='是否平台管理员')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='最近登录时间', null=True)),
                ('last_tenant_id', models.BigIntegerField(blank=True, help_text='最近访问的租户ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'global_user',
                'indexes': [models.Index(fields=['status'], name='idx_global_user_status'), models.Index(fields=['is_platform_admin'], name='idx_global_user_admin')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_hash', models.CharField(help_text='refresh token 哈希存储（唯一）', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', '活跃'), ('REVOKED', '已撤销'), ('EXPIRED', '已过期')], default='ACTIVE', help_text='会话状态：ACTIVE=活跃，REVOKED=已撤销，EXPIRED=已过期', max_length=16)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, help_text='签发时间')),
                ('expires_at', models.DateTimeField(help_text='过期时间')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='撤销时间', null=True)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='设备信息（ua/ip/device_id）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', help_text='关联的平台用户', on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='accounts.globaluser')),
            ],
            options={
                'db_table': 'auth_session',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_auth_session_user'), models.Index(fields=['expires_at'], name='idx_auth_session_expires')],
            },
        ),
    ]
